Trex2champ converter for obtaining champ input files
TREX-CoE/trexio_tools pull request #1
Opened 2021-10-29 14:13 UTC by neelravi

Obtaining champ input files from trexio hdf5 file or trexio text directory. 
resultsFile package is currently being used to get determinants data.

Files generated using this converter include
- geometry
- determinants
- symmetry
- orbitals
- ecp

2021-10-31 12:18 UTC, q-posev requested changes
Thank you for your work @neelravi ! 
I had only one major comment regarding two identical sets of ECP files and then 2 minor questions.

2021-10-31 12:18 UTC, q-posev commented on src/trex2champ.py
> +    write_champ_file_ecp_trexio(filename, nucleus_num, nucleus_label, ecp_num, ecp_z_core, ecp_max_ang_mom_plus_1, ecp_ang_mom, ecp_nucleus_index, ecp_exponent, ecp_coefficient, ecp_power)
This call looks identical to the `write_champ_file_ecp` below. Moreover, I checked and the `trex2champ` converter produces two identical sets of ECP files with the only difference that one set contains `trexBFD` prefix in the filenames while the other one contains only `BFD`.

If `write_champ_file_ecp` and `write_champ_file_ecp_trexio` functions do essentially the same thing, then maybe one of them can be safely removed. If one of them serves the debug purposes, then you can add an optional keyword to to call it.

2021-10-31 12:18 UTC, q-posev commented on src/trex2champ.py
> +    the quantum chemistry calculation to a champ v2.0 format file.
Does CHAMP has its dedicated file format? Or `v2.0` correspond to TREXIO here?

2021-10-31 12:18 UTC, q-posev commented on src/trex2champ.py
> +                filename_ecp = "BFD." + 'gauss_ecp.dat.' + nucleus_label[ind]
This function only produces Gaussian-like ECP files. 
Since CHAMP can read ECP files in GAMESS format too, could it be useful to add an additional keyword to allow the user to choose between ECP formats produced by the converter? The difference between GAMESS and Gaussian ECP format is in the header, if I understand it correctly.

2021-11-01 09:19 UTC, q-posev commented on src/trex2champ.py
> +                    lmax_plus_one = pseudo[ind].get("lmax") + 1
I also noticed that the second line in produced ECP files (both `BFD.gauss_ecp.dat.C` and `trexBFD.gauss_ecp.dat.C`) for carbon atom is 2. Does it correspond to value `lmax+1` ?

If it does, then there is a bug in the trex2champ converter. For carbon, `lmax+1` is 1, since only 2 core electrons in S orbital are removed. This can be checked by examining the `GAMESS_CAS.log` file. Also `max_ang_mom_plus_1` in the produced TREXIO file is 1 for carbons. This can be fixed by replacing line 348 with
`                    lmax_plus_one = pseudo[ind].get("lmax")`

2021-11-01 09:30 UTC, q-posev commented on src/trex2champ.py
> +                    file.write("BFD {:s} pseudo \n".format(unique_elements[i]))
Same comment as above, here instead of counting unique elements, one has to use `max_ang_mom_plus_1` obtained from the TREXIO file.
By looking at [this Gaussian09 example](http://thiele.ruc.dk/~spanget/help/g09/k_pseudo.htm), it seems that you are missing number of core electrons in the produced ECP files. Also, based on the same page, first line should also contain the `lmax+1` value (in Gaussian09 ECP file format: `Name,Max,ICore`).

2021-11-01 10:04 UTC, neelravi commented on src/trex2champ.py
> +                    lmax_plus_one = pseudo[ind].get("lmax") + 1
The second line in the ECP file contains redundant information. It tells how many l components are present in the file. For example, for carbon l=1, and l=0 (hence 2).
For hydrogen, it is 1 (l=0) only.

2021-11-01 10:06 UTC, neelravi commented on src/trex2champ.py
> +                filename_ecp = "BFD." + 'gauss_ecp.dat.' + nucleus_label[ind]
As far as I know, champ reads from this Gaussian-like file format only. (it was generated by an older perl converter.) There are other options also available inside the code but they are not popular and not maintained.

2021-11-01 10:07 UTC, neelravi commented on src/trex2champ.py
> +    the quantum chemistry calculation to a champ v2.0 format file.
The format looks very similar to Gaussian-type, but yes, it is specific to champ. The v2.0 corresponds to champ v2.0.

2021-11-01 10:09 UTC, neelravi commented on src/trex2champ.py
> +    write_champ_file_ecp_trexio(filename, nucleus_num, nucleus_label, ecp_num, ecp_z_core, ecp_max_ang_mom_plus_1, ecp_ang_mom, ecp_nucleus_index, ecp_exponent, ecp_coefficient, ecp_power)
I will delete the portion of the code where ECP files are generated from the resultsFile package as it is exactly the same and everything should come from trexio files eventually.

2021-11-01 10:27 UTC, q-posev commented on src/trex2champ.py
> +    write_champ_file_ecp_trexio(filename, nucleus_num, nucleus_label, ecp_num, ecp_z_core, ecp_max_ang_mom_plus_1, ecp_ang_mom, ecp_nucleus_index, ecp_exponent, ecp_coefficient, ecp_power)
Great, thank you!

2021-11-01 10:28 UTC, q-posev commented on src/trex2champ.py
> +    the quantum chemistry calculation to a champ v2.0 format file.
Thanks for the clarification!

2021-11-01 10:31 UTC, q-posev commented on src/trex2champ.py
> +                    lmax_plus_one = pseudo[ind].get("lmax") + 1
I see, so it is a format specific to CHAMP. Then there is no problem to keep it, I assumed that CHAMP can read ECP files in GAMESS format.

2021-11-01 10:33 UTC, q-posev approved these changes

2021-11-01 10:33 UTC, merged