motype option specified when parsing data from gamess
TREX-CoE/trexio_tools pull request #3
Opened 2022-02-16 14:02 UTC by neelravi

Hi!,
When using the convert-from tool, I needed to choose the type of molecular orbitals to be written into the hdf5 file. I have created a command-line option for that. 
Also, all the available MOs are read for that given type (the split-up of closed + virtual + active) is replaced by a loop over all the MOs.

2022-02-16 21:32 UTC, scemama requested changes

2022-02-16 21:32 UTC, scemama commented on src/converters/convert_from.py
> +def run_resultsFile(trexio_filename, filename, motype, back_end):
Can you set `motype=None` here to make the argument optional?

2022-02-16 21:32 UTC, scemama commented on src/converters/convert_from.py
> +        MO_type = motype.upper()
I am not sure that `upper` is correct, because `MO_type` can be `"Natural"`

2022-02-16 21:32 UTC, scemama commented on src/converters/convert_from.py
> +def run(trexio_filename, filename, filetype,  motype, back_end):
Can you make it optional here also?

2022-02-16 21:32 UTC, scemama commented on src/trexio_tools/trexio_run.py
> +      trexio convert-from   -t type -i input_file -x orbital_type [-b back_end]  TREXIO_FILE
You can use `[-x orbital_type]` to make it optional here

2022-02-16 21:32 UTC, scemama commented on src/trexio_tools/trexio_run.py
> +    import pprint; pprint.pprint(args)
Can you remove that line?

2022-02-16 21:32 UTC, scemama commented on src/trexio_tools/trexio_run.py
> +        motype = 'NATURAL'
We need to be careful here because if the MOs are not consistent with the determinants, the file will be all wrong. We should let resultsFile decide here which MOs are the correct ones if `--motype` is `None`. You can leave `motype=None` and let it propagate to the `run_resultsFile` function.

2022-02-17 08:27 UTC, neelravi commented on src/converters/convert_from.py
> +def run_resultsFile(trexio_filename, filename, motype, back_end):
`motype=None` done.

2022-02-17 08:28 UTC, neelravi commented on src/converters/convert_from.py
> +        MO_type = motype.upper()
Corrected with `MO_type = motype`

2022-02-17 08:29 UTC, neelravi commented on src/converters/convert_from.py
> +def run(trexio_filename, filename, filetype,  motype, back_end):
Done. I needed to change the order of arguments too.
`def run(trexio_filename, filename, filetype, back_end, motype=None):`

2022-02-17 08:29 UTC, neelravi commented on src/trexio_tools/trexio_run.py
> +      trexio convert-from   -t type -i input_file -x orbital_type [-b back_end]  TREXIO_FILE
I never knew this is how it works. Thanks! made it optional

2022-02-17 08:30 UTC, neelravi commented on src/trexio_tools/trexio_run.py
> +    import pprint; pprint.pprint(args)
debug printing removed.

2022-02-17 08:31 UTC, neelravi commented on src/trexio_tools/trexio_run.py
> +        motype = 'NATURAL'
Change the above portion to

```
   if args["--motype"] is not None:
        motype = str(args["--motype"])
    else:
        motype = None
```

2022-02-17 09:02 UTC, q-posev commented on src/trexio_tools/trexio_run.py
> +        motype = 'NATURAL'
We can safely remove the aforementioned code. You can use `motype=args["--motype"]` in the arguments list of the `run` function, i.e.
```
    elif args["convert-from"]:
        from converters.convert_from import run
        run(args["TREXIO_FILE"], args["--input"], args["--type"], back_end=back_end, motype=args["--motype"])
```

2022-02-17 09:08 UTC, q-posev commented on src/converters/convert_from.py
> -    try:
I am a bit concerned about removing the MO processing, which has been already debugged. Would it be possible to refactor this part so that we keep the old code for the case `if motype is None`; `else` process it according to your code?

2022-02-17 09:10 UTC, q-posev commented on src/converters/trex2champ.py
Nice catch of the hard-coded `back_end=trexio.TREXIO_HDF5` !

2022-02-17 09:15 UTC, neelravi commented on src/trexio_tools/trexio_run.py
> +        motype = 'NATURAL'
sounds good to me.

2022-02-17 09:19 UTC, q-posev reviewed
Thank you @neelravi ! I left a few comments/suggestions in this PR.

However, I remember that Kousuke started working on the natural orbital support in `resultsFile`.  If this is the case, than maybe your efforts can be merged somehow? This can be discussed during the WP2 meeting.

2022-02-17 09:21 UTC, q-posev commented on src/trexio_tools/trexio_run.py
> +        motype = 'NATURAL'
You are right, my bad!

2022-02-17 09:26 UTC, neelravi commented on src/converters/convert_from.py
> -    try:
In the following original portion of the code, the MOs are classified and then added up. The closed, active, and virtual are not referred to when writing the MO coefficients. This might fail if I want all the MOs, but res.closed_mos + res.virtual_mos + res.active_mos do not add up to the total. 
Since we intend to write all the MOs to hdf5 anyway, why do we need to worry about the classification?
```
    try:
        closed  = [(allMOs[i].eigenvalue, i) for i in res.closed_mos]
        virtual = [(allMOs[i].eigenvalue, i) for i in res.virtual_mos]
        active  = [(allMOs[i].eigenvalue, i) for i in res.active_mos]
    except:
        closed  = []
        virtual = []
        active  = [(allMOs[i].eigenvalue, i) for i in range(len(allMOs))]

    closed  = [x[1] for x in closed]
    active  = [x[1] for x in active]
    virtual = [x[1] for x in virtual]
    MOindices = closed + active + virtual

```

2022-02-17 09:35 UTC, q-posev commented on src/trexio_tools/trexio_run.py
> +        motype = 'NATURAL'
@neelravi I just checked and my proposed change works fine. This is because if the `motype` is not specified in the command line then `args["--motype"] is None`, which is what you use in your `if else`. So this can go directly in the arguments list :100:

2022-02-17 09:37 UTC, neelravi commented on src/trexio_tools/trexio_run.py
> +        motype = 'NATURAL'
Awesome! I will patch it.

2022-02-17 09:43 UTC, q-posev commented on src/converters/convert_from.py
> -    try:
I see. We might need this separation of closed/active/virtual MOs later for working with the CI determinants. May I ask you to comment the aforementioned code for now so that it is not lost?

2022-02-17 09:44 UTC, neelravi commented on src/converters/convert_from.py
> -    try:
Okay. I will do that.

2022-02-21 16:48 UTC, merged