Improve force overwriting for existing output files
TREX-CoE/trexio_tools pull request #48
Opened 2024-11-10 09:53 UTC by q-posev

- Fixes #41 

Mainly moved the file removal logic to the high-level `trexio_run.py` script and fixed some inconsistencies. No it calls `rm -rf` so it should work for both TEXT and HDF5 back ends unlike the previous version that was printing an error message for TEXT TREXIO files.

2024-11-10 16:21 UTC, scemama commented on src/trexio_tools/trexio_run.py
> +
Suppose that a user calls `trexio_convert -w $HOME/$MY_TREXIO_FILE`, this wil call `rm -rf -- $HOME/$MY_TREXIO_FILE`. If the user made a mistake in his/her script and forgot to define `$MY_TREXIO_FILE`, it wil make `rm -rf $HOME/`. :-(
It would be safer to try to open the trexio file first and check something inside it like the trexio metadata, so that we are sure that the thing we remove is indeed a trexio file.

2024-11-10 16:22 UTC, scemama requested changes
Great! But there is a little danger with `rm -rf`. See my comment on the source file.

2024-11-10 17:41 UTC, q-posev commented
Great idea! Will do that.

2024-11-10 20:02 UTC, q-posev commented on src/trexio_tools/trexio_run.py
> +
Done, please have a look.

2024-11-11 02:30 UTC, scemama approved these changes

2024-11-11 02:30 UTC, merged